---
- name: attach volume 
  ec2_vol: 
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    ec2_region: "{{ AWS_REGION }}"  
    zone: "{{ AWS_ZONE }}"
    instance: "{{ ec2.instances[0].id }}"
    id: "{{ vol_info.volume_id }}"
    device_name: /dev/xvdf
    delete_on_termination: no
