---
- name: Create new EBS volume 
  ec2_vol: 
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    ec2_region: "{{ AWS_REGION }}"
    zone: "{{ AWS_ZONE }}"
    volume_size: "1"
    name: my_vol
    device_name: /dev/xvdf
  register: vol_info


    
