---
- name: Stop instances before creating AMI
  ec2: 
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    ec2_region: "{{ AWS_REGION }}"
    instance_id: "{{ hostvars[groups['webgroup'][0]]['ansible_ec2_instance_id'] }}"
    state: stopped
    wait: yes
  
- name: Create AMI 
  ec2_ami: 
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    ec2_region: "{{ AWS_REGION }}"
    instance_id: "{{ hostvars[groups['webgroup'][0]]['ansible_ec2_instance_id'] }}"
    name: wencontentAMI
    state: present
 
